### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pratibha-kadam** [gaarangoa/deeparg2.0#11]
Hello There,

I am trying to use deeparg download_data -o ./ command

it throws error of HTTPconnection error
![Screenshot from 2023-08-01 16-19-19](https://github.com/gaarangoa/deeparg2.0/assets/88572259/bcb1c71e-94dc-400a-b71b-52e0d8ff5fe0)

**Comment by gaarangoa** [comment]
please use https://github.com/gaarangoa/deeparg
